import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Miroir Révélateur",
    description: "Ce miroir ancien révèle votre véritable nature lorsque vous vous y regardez.",
    price: 129.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "Artefacts",
    isNew: true,
    magicLevel: 4,
  },
  {
    id: "2",
    name: "Grimoire des Secrets",
    description: "Un livre ancien contenant des sorts et des formules magiques oubliés.",
    price: 89.5,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Livres",
    isNew: false,
    magicLevel: 3,
  },
  {
    id: "3",
    name: "Pendentif de Protection",
    description: "Ce pendentif en argent vous protège contre les énergies négatives.",
    price: 59.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    category: "Bijoux",
    isNew: false,
    magicLevel: 2,
  },
  {
    id: "4",
    name: "Boule de Cristal Divinatoire",
    description: "Une boule de cristal authentique pour voir l'avenir et communiquer avec l'au-delà.",
    price: 199.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Divination",
    isNew: false,
    magicLevel: 5,
  },
  {
    id: "5",
    name: "Baguette en Bois d'Olivier",
    description: "Baguette magique taillée dans du bois d'olivier millénaire.",
    price: 75.0,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Baguettes",
    isNew: true,
    magicLevel: 4,
  },
  {
    id: "6",
    name: "Amulette de Chance",
    description: "Cette amulette en jade augmente considérablement votre chance au quotidien.",
    price: 45.99,
    discount: 20,
    image: "/placeholder.svg?height=400&width=400",
    category: "Bijoux",
    isNew: false,
    magicLevel: 2,
  },
  {
    id: "7",
    name: "Chandelier Flottant",
    description: "Un chandelier enchanté qui flotte dans les airs et s'allume à votre commande.",
    price: 149.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Décoration",
    isNew: true,
    magicLevel: 3,
  },
  {
    id: "8",
    name: "Potion de Rêves Lucides",
    description: "Cette potion vous permet de contrôler vos rêves pendant votre sommeil.",
    price: 39.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Potions",
    isNew: false,
    magicLevel: 3,
  },
  {
    id: "9",
    name: "Tapis Volant Miniature",
    description: "Un petit tapis décoratif qui peut réellement léviter à quelques centimètres du sol.",
    price: 299.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    category: "Transport",
    isNew: false,
    magicLevel: 5,
  },
  {
    id: "10",
    name: "Montre qui Ralentit le Temps",
    description: "Cette montre vintage peut ralentir le temps autour de vous pendant quelques secondes.",
    price: 499.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessoires",
    isNew: true,
    magicLevel: 5,
  },
  {
    id: "11",
    name: "Plume d'Écriture Automatique",
    description: "Cette plume écrit toute seule sous l'influence de votre pensée.",
    price: 69.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "Écriture",
    isNew: false,
    magicLevel: 2,
  },
  {
    id: "12",
    name: "Lanterne des Âmes",
    description: "Une lanterne qui émet une lumière capable de révéler les présences invisibles.",
    price: 119.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Éclairage",
    isNew: false,
    magicLevel: 4,
  },
  {
    id: "13",
    name: "Sablier Inversé",
    description: "Un sablier qui s'écoule de bas en haut, défiant les lois de la gravité.",
    price: 89.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Artefacts",
    isNew: false,
    magicLevel: 3,
  },
  {
    id: "14",
    name: "Clé des Passages",
    description: "Cette clé en bronze peut ouvrir n'importe quelle serrure une fois par jour.",
    price: 159.99,
    discount: 25,
    image: "/placeholder.svg?height=400&width=400",
    category: "Outils",
    isNew: true,
    magicLevel: 4,
  },
  {
    id: "15",
    name: "Encre Invisible",
    description: "Une encre qui n'apparaît que sous la lumière de la lune ou à la lecture d'une formule magique.",
    price: 29.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Écriture",
    isNew: false,
    magicLevel: 2,
  },
  {
    id: "16",
    name: "Boussole des Désirs",
    description: "Cette boussole ne pointe pas vers le nord, mais vers ce que vous désirez le plus au monde.",
    price: 129.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Navigation",
    isNew: false,
    magicLevel: 3,
  },
  {
    id: "17",
    name: "Carillon Apaisant",
    description: "Un carillon qui apaise l'esprit et chasse les cauchemars lorsqu'il tinte.",
    price: 49.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    category: "Décoration",
    isNew: false,
    magicLevel: 2,
  },
  {
    id: "18",
    name: "Dague de Vérité",
    description: "Cette dague ancienne oblige quiconque est touché par sa lame à dire la vérité pendant une heure.",
    price: 249.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Armes",
    isNew: false,
    magicLevel: 4,
  },
  {
    id: "19",
    name: "Flacon d'Eau Élémentaire",
    description:
      "Un flacon contenant de l'eau pure du royaume élémentaire, capable de purifier n'importe quelle substance.",
    price: 79.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Potions",
    isNew: true,
    magicLevel: 3,
  },
  {
    id: "20",
    name: "Couronne de Télépathie",
    description: "Cette couronne en argent permet de communiquer par la pensée avec quiconque la porte également.",
    price: 349.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "Bijoux",
    isNew: false,
    magicLevel: 5,
  },
]
